- AzFilesHybrid/AzFilesHybrid.psm1
This PR fixes adds missing `-Server` parameters to the AD cmdlets in the password rotation cmdlets so they work in the case the user's workstation is in a different domain than their storage account.
Additionally, fix an incidental TLS issue that occurs on older versions of Windows 10 (such as Windows Server 2016).
> Add missing server parameter to password rotation commands

- ScanUnsupportedChars/ScanUnsupportedChars.ps1
- ScanUnsupportedChars/readme.md
As discussed via Mail, this gives options to the script to copy over files via robocopy if file names are not supported.
This allows alternative backup drops for such files. The relative location SharePath as origin will be preserved in the destination path (new parameter). Because of the Unicode support, the options of passing parameters had been a bit restrictive.
If you know/have a better solution for the workaround, please feel free to reject with some hints. Start-Process does not allow redirection to $null or append redirected output.
> Added RoboCopy capabilities

- AzFileDiagnostics/Windows/AzFileDiagnostics.ps1
LmCompatibilityLevel is checked against the exact value 3, while any number greater than 3 will work
> Improved check for LmCompatibilityLevel

- AzFilesHybrid/AzFilesHybrid.psm1
AAD Graph is being deprecated, migrate to MS graph.
A few difference from MS graph
- OnPremisesSecurityIdentifier wont return by MS graph by default, need to explicitly add it. 
$aadObject = Get-MgUser -UserId $assignment.ObjectId -Property OnPremisesSecurityIdentifier
- Get-MgDirectoryObjectById should be the alternative of Get-AzureADObjectByObjectId. 
However, its invoke action getByIds, This API has a known issue. Not all directory objects returned are the full objects 
containing all their properties.[Link](https://learn.microsoft.com/en-us/graph/api/directoryobject-getbyids?view=graph-rest1.0&tabs=http#:~:text=This%20API%20has%20a%20known%20issue.%20Not%20all%20directory%20objects%20returned%20)
I used Get-MgUser and Get-MgGroup to work around
- Id is the domain name in …
> Migrate power shelll to MS graph

- SMBDiagnostics/smbclientlogs.sh
This info is useful to compare with the last reboot time. In some cases, we want to make sure that the system was rebooted after upgrading keyutils.
> Get the package install date for keyutils and cifs-utils packages.

- SMBDiagnostics/smbclientlogs.sh
+ Remove the cifs.ko check, since mount can load the module automatically.
+ Don't clear dmesg initially.
> Remove the cifs.ko check, don't clear dmesg

- SMBDiagnostics/smbclientlogs.sh
Right now we enable cifsFYI logs unconditionally when capturing diagnostics. But this makes changes to debugfs, which will not be possible with kernel lockdown enabled, and that is the default with trusted VMs which are becoming more common.
Additionally, we do not use verbose logs much for our debugging. We have grown to use trace-cmd more.
This change disables verbose logging by default.
No need to document this. It will complicate the instructions for the customers. Instruct customers specially when verbose logs are needed.
> Do verbose logging only when instructed.

- AzFilesHybrid/AzFilesHybrid.psm1
Added a Reg Key check for ADDS. If the Reg key is enabled for AD DS there is an issue in retrieving the Kerberos tickets.
> Reg Key check for AD DS

- SMBDiagnostics/README
- SMBDiagnostics/smbclientlogs.sh
The script now relies on the output of the ss command. However, in the initial check for utilities, this tool is not checked. 
This change checks for the utility. If not present, it errors out.
> Add an utils check for the ss command

- NfsDiagnostics/README
When a part of the README file was updated to reflect the standard set of steps, we replaced nfsclientlogs.sh with smbclientlogs.sh in one location. Fixed it here.
> Fix typo in README file for NfsDiagnostics.

- AzFilesHybrid/AzFilesHybrid.psm1
`$domain` is already used by the parameter, so reassigning in the `foreach` leads to weird implicit conversions
> Fix regkey check

- SMBDiagnostics/smbclientlogs.sh
We do not print these details today, which is critical for some DNS resolution issues.
> Print package version details for keyutils and cifs-utils

- RestSetAcls/README.md
https://www.powershellgallery.com/packages/RestSetAcls/0.1.1
> Update installation instructions for install from PSGallery

- AzFilesHybrid/AzFilesHybrid.psd1
Added PSStyle module to required modules
- Allows for the use of PSStyle variable in versions that do not have it, such as PowerShell 5
> added PSStyle to required modules

- AzFilesHybrid/AzFilesHybrid.psm1
- Fix issues with RBAC detection
- Fix bug where MgGraph and Az aren't connected to the same tenant ID when running the command
- Improve RBAC success case messages 
- Fix issue in RBAC check where a stack trace is printed if no username is passed. Print a nicer error message instead.
- Change `UserPrincipalName` param to `UserName`. That way, if you forget to provide it in either `Debug-AzStorageAccountEntraKerbAuth` or `Debug-AzStorageAccountAuth`, the fix is the same. The fact that the UserName is a UserPrincipalName is clarified in the help message
- Fix some spacing issues
- Fix some help messages
- Fix detection of null objectid
> Minor fixes to RBAC check

- .github/workflows/RestSetAcls.yml
- RestSetAcls/RestSetAcls/SddlUtils.ps1
- RestSetAcls/build.depend.psd1
- RestSetAcls/publish-tools.psm1
The cast from `AceFlags` to `int` can be done implicitly on PowerShell 7, but not 5. This makes the cast explicit, so that it also works in PowerShell 5, and adds testing on PowerShell 5 to catch such errors next time
> Fix RestSetAcls compatibility with PowerShell 5

- AzFilesHybrid/AzFilesHybrid/AzFilesHybrid.psm1
The `-UseBasicParsing` switch is required on PowerShell 5 for Server Core; it has no effect on PowerShell 7. 
See [PowerShell 5 documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-5.1#parameters):
> ## `-UseBasicParsing`
> Indicates that the cmdlet uses the response object for HTML content without Document Object Model (DOM) parsing. This parameter is required when Internet Explorer is not installed on the computers, such as on a Server Core installation of a Windows Server operating system.
See [PowerShell 7 documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.4#parameters):
> ## `-UseBasicParsing`
> This parameter has been …
> Fix CheckAADConnectivity for Server Core + PowerShell 5

- AzFilesHybrid/readme.md
- Prerequisites 
- Installation: 2 options for installing, either from PSGallery or from Zip file
- Uninstall: Instructions for uninstalling based on the installation chosen previously
> Readme Update - Draft 1

- RestSetAcls/RestSetAcls/RestSetAcls.psd1
- RestSetAcls/RestSetAcls/RestSetAcls.psm1
- RestSetAcls/RestSetAcls/SddlUtils.ps1
- RestSetAcls/docs/Restore-AzFileAclInheritance.md
- RestSetAcls/test/integration/RestSetAcls.Tests.ps1
- RestSetAcls/test/unit/SddlUtils.Tests.ps1
Add an option to reset all child folders, such that they only contain permissions inherited from parent.
> Add -Reset switch to Restore-AzFileAclInheritance

- RestSetAcls/RestSetAcls/RestSetAcls.psm1
Add `-ErrorAction Stop`, as it's a terminal error
> Improve handling when Get-AzStorageFile fails
