Azure-Samples/azure-files-samples

point-to-site-vpn-azure-files/README.md

* Fixing typo in README file
```
[ ] Yes
[x] No
```
What kind of change does this Pull Request introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```
* Test the code
```
```
Verify that the following are valid
* ...

Fix typo with lookup

---

point-to-site-vpn-azure-files/README.md

* Correct a typo in the Point-to-Site VPN sample.
```
[ ] Yes
[x] No
```
What kind of change does this Pull Request introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

Fixed typo of "nslookup"

---

AzFilesHybrid/CopyToPSPath.ps1

Add copy script for user installation.

Add copy script

---

AzFileDiagnostics/Linux/AzFileDiagnostics.sh

Also made a few changes to the script:
1. Check that all the tools that we use in the script are installed on the client.
2. Check that cifs-utils version is at least 6.8
3. Fixed the kernel version comparison operation to check if has the idle timeout fix.
4. Fixed the message in case of unsuccessful mount. It was very misleading.
5. Checking the stderr for permission denied for the mount command instead of asking the customer the error they saw.
6. Made region mismatch logging print the IP address detected.

Moved AzFileDiagnostics.sh script into this git repo.

---

AzFileDiagnostics/Linux/AzFileDiagnostics.sh

Modify Diagnostics script to add SLES 12 SP2 support for SMB 3.0

Modify Diagnostics script to add SLES 12 SP2 support for SMB 3.0

---

AzFileDiagnostics/Linux/readme.md
AzFileDiagnostics/Windows/readme.md
AzFilesHybrid/AzFilesHybrid.psd1
AzFilesHybrid/AzFilesHybrid.psm1
ScanUnsupportedChars/ScanUnsupportedChars.ps1
ScanUnsupportedChars/readme.md
dns-forwarder/azuredeploy.json

Since some of the distro versions in the diagnostics script have hit a EOL for distro support, we revised the minimum supported versions during our last change. However, the public documentations including the readme file here used the old info. 
Updating that info in this PR.

Update the minimum supported distro versions in the readme as per the script

---

ScanUnsupportedChars/ScanUnsupportedChars.ps1

Adding support to check if a supported control char works with combination of other chars

Control char REST api check

---

FileSyncErrorsReport/FileSyncErrorsReport.ps1
FileSyncErrorsReport/readme.md

Make the FileSyncErrorsReport script version v12 available to customer which are unable to use the most recent version of the script, (v13 and higher).

Add FileSyncErrorsReport

---

AzFileDiagnostics/Linux/AzFileDiagnostics.sh

Fix typo in AzFileDiagnostics.sh

---

NfsDiagnostics/README
NfsDiagnostics/nfsclientlogs.sh
NfsDiagnostics/trace-nfsbpf
SMBDiagnostics/README
SMBDiagnostics/smbclientlogs.sh
SMBDiagnostics/trace-cifsbpf

NFS Diagnostics script to collect logs for debugging

Added Diagnostics scripts to debug customer issues

---

autogrow-PFS-quota/ARMtemplate.json

- Added Environment and Subscription parameters to Connect-AzAccount to be inclusive of other clouds and streamlined the Azure context
- Removed Set-AzContext since its set with Connect-AzAccount
- Moved Connect-AzAccount after the import of its module
- Moved Write-Host for "New Provisioned Capacity" inside the IF block
- Removed the New-AzStorageContext since it wasn't needed, and the variable is not referenced.
- Fixed JSON formatting

Fixed PowerShell script for "Autoincrease Premium File Share Quota"

---

AzFileDiagnostics/Windows/AzFileDiagnostics.ps1
AzFileDiagnostics/Windows/readme.md
AzFileDiagnostics/Windows/sample-output/sample-output.txt

1. Validate SMB versions
2. Validate autheniticate mechanism
3. Validate channel encryption settings
4. Notify user about type of encryption configured for Kerbros ticket
5. In case of SMB2.1, Check secure transfer option is enabled and notify user
Minor bug fixes and logs

Add following validations based on azure storage account settings for windows clients

---

AzFileDiagnostics/Windows/AzFileDiagnostics.ps1

Handle a case when Get-AzStorageFileServiceProperty returns NULL for some properties

Handle case for az cmd for windows file diag script

---

AzFilesHybrid/AzFilesHybrid.psm1

Added DefaultSharePermission check to the Debug-AzStorageAccountAuth command.

AzFilesHybrid.psm1/Debug-AzStorageAccountAuth checks DefaultSharePermission

---

AzFilesHybrid/AzFilesHybrid.psm1

Xstore and XRP code are already supporting AES256 for user account in AD.

add AES256 support for user account

---

AzFilesHybrid/AzFilesHybrid.psd1
dns-forwarder/azuredeploy.json

Update module version for AES 256 change

update module version

---

AzFilesHybrid/AzFilesHybrid.psm1

Change AES256 encryption type as default when we create AD object.

set AES256 as default

---

AzFilesHybrid/AzFilesHybrid.psm1

Block cmdlets for AADDS or AADKERB

Block cmdlets for AADDS or AADKERB

---

AzFilesHybrid/AzFilesHybrid.psm1

Reverts Azure-Samples/azure-files-samples#115

Revert "Block cmdlets for AADDS or AADKERB"

---

AzFilesHybrid/AzFilesHybrid.psm1

- Fix typo
- included a better error message for 'Full Control' Permission issue

Misc Powershell Improvements minor updates

---

AzFilesHybrid/AzFilesHybrid.psm1

Debug-KerberosTicketEncryption fixes and remove unnecessary fix for PS7

Debug-KerberosTicketEncryption fixes and remove unnecessary fix for PS7

---

AzFilesHybrid/AzFilesHybrid.psm1

Fixes issues when parsing klist results

checkKerberosTicketEncryption fix

---

SMBDiagnostics/smbclientlogs.sh

1. Get CIFS kernel module information
2. Get mount.cifs helper version information
3. zip is one of the dependency for this script, check if it's installed before proceeding

Capture cifs kernel module and cifs utils version information

---

AzFileDiagnostics/Linux/AzFileDiagnostics.sh

Take Azure subscription as an input, if server validation is selected.
Soon after az login, set this subscription as the default.

Set active subscription when dealing with az cli

---

NfsDiagnostics/README
NfsDiagnostics/nfsclientlogs.sh
SMBDiagnostics/README

The README files were out-of-date with the new changes. Updated them and reformatted.

Updated the README files with the updated instructions.

---

SMBDiagnostics/smbclientlogs.sh

- Dump script progress/errors into stdout
- Remove log directory only if it exists
- Check that we're root
- Check to see that tcpdump exists
- Fix rpm/apt check for package install details

Fix minor errors in smbclientlogs.sh

---

AzFileDiagnostics/Windows/SmbClientLogs.ps1

Update Public Facing SmbClientLogs.ps1 to version 3.61 that SQL-EP is running in their production

Update Public Facing SmbClientLogs.ps1 to version 3.61 that SQL-EP is running in their production

---

AzFileDiagnostics/Windows/SmbClientLogs.ps1

Fix -CaptureNetwork switch in SmbClientLogs.ps1

Fix -CaptureNetwork switch in SmbClientLogs.ps1

---

AzFilesHybrid/AzFilesHybrid.psm1

[added 2 checks AAD connectivity and 445]

Debug adding check1

---

AzFilesHybrid/AzFilesHybrid.psm1
SMBDiagnostics/smbclientlogs.sh

Debug check2

---

NfsDiagnostics/nfsclientlogs.sh

Add OS information
Add NFS specific diagnostics
Add system, process, mount info, misc information needed for analyzing trace-cmd data etc
Error handling and dependencies check

Update NFS diag script to capture additional disgnostics and fix bugs

---

AzFilesHybrid/AzFilesHybrid.psm1

Did a change in the spn value in admin consent check

change in the spn value in admin consent check

---

AzFilesHybrid/AzFilesHybrid.psm1

update text for Domain joined check

update text for Domain joined check

---

AzFilesHybrid/AzFilesHybrid.psm1

made a minor change in the code

Adminconsentminorchange

---

AzFilesHybrid/AzFilesHybrid.psm1

made some changes on the PR 168

Addcomments168 pr

---

ScanUnsupportedChars/ScanUnsupportedChars.ps1

Updating Xsync scanner script to reflect latest supported chars

Update XSync scanner script to latest supported chars

---

AzFilesHybrid/AzFilesHybrid.psm1

Checks that the right version of Microsoft.Graph is installed before calling relatively new functionality

Add check for min Microsoft.Graph version

---

AzFilesHybrid/AzFilesHybrid.psd1

Getting ready for 0.3.0 release

Bump AzFilesHybrid to 0.3.0

---

AzFilesHybrid/AzFilesHybrid.psm1

created New Windows Checks for WinHttpAutoProxySvc and iphlpsvc Services

New Windows Checks for WinHttpAutoProxySvc and iphlpsvc Services

---

AzFilesHybrid/AzFilesHybrid.psm1

We forgot to check the `HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters` path for AD DS. 
To fix this, I extracted the Entra Kerb code into a shared function. The shared implementation also means that future improvements will go to both AD DS and Entra Kerb checks.

Fix AD DS Kerberos reg key check

---

RestSetAcls/CONTRIBUTING.md
RestSetAcls/RestSetAcls/RestSetAcls.psd1
RestSetAcls/RestSetAcls/RestSetAcls.psm1
RestSetAcls/publish-psgallery.ps1

Fix Context type to be compatible with newer Azure.Storage versions.

RestSetAcls v0.1.2

---

RestSetAcls/RestSetAcls/RestSetAcls.psm1
RestSetAcls/RestSetAcls/SddlUtils.ps1
RestSetAcls/test/SddlUtils.Tests.ps1

Adds tooling for debugging, simplifies conversions between various formats, and adds a few tests

Improve RestSetAcls SDDL utils

---

RestSetAcls/RestSetAcls/RestSetAcls.psd1
RestSetAcls/RestSetAcls/RestSetAcls.psm1
RestSetAcls/build-tools.psm1
RestSetAcls/test/integration/RestSetAcls.Tests.ps1

Recent refactors broke this. Fixing it, and adding test coverage to prevent this in the future.

Fix RestSetAcls Set-AzFileAclRecursive

---

RestSetAcls/README.md
RestSetAcls/RestSetAcls/RestSetAcls.psd1
RestSetAcls/RestSetAcls/RestSetAcls.psm1
RestSetAcls/docs/Restore-AzFileAclInheritance.md
RestSetAcls/docs/Set-AzFileAclRecursive.md
RestSetAcls/test/integration/RestSetAcls.Tests.ps1

Add `-PassThru` and `-Silent` to improve scriptability

Add -PassThru and -Silent switches
